/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Wed Feb 28 18:43:05 2018. */

#ifndef PB_SECRET_NUMBER_PB_H_INCLUDED
#define PB_SECRET_NUMBER_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _SecretNumber {
    bool has_value;
    int32_t value;
/* @@protoc_insertion_point(struct:SecretNumber) */
} SecretNumber;

/* Default values for struct fields */

/* Initializer values for message structs */
#define SecretNumber_init_default                {false, 0}
#define SecretNumber_init_zero                   {false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SecretNumber_value_tag                   1

/* Struct field encoding specification for nanopb */
extern const pb_field_t SecretNumber_fields[2];

/* Maximum encoded size of messages (where known) */
#define SecretNumber_size                        11

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SECRET_NUMBER_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
