/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Wed Feb 28 18:43:05 2018. */

#include "secret_number.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SecretNumber_fields[2] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, SecretNumber, value, value, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
