# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secret_number.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='secret_number.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13secret_number.proto\"\x1d\n\x0cSecretNumber\x12\r\n\x05value\x18\x01 \x01(\x05')
)




_SECRETNUMBER = _descriptor.Descriptor(
  name='SecretNumber',
  full_name='SecretNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='SecretNumber.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['SecretNumber'] = _SECRETNUMBER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SecretNumber = _reflection.GeneratedProtocolMessageType('SecretNumber', (_message.Message,), dict(
  DESCRIPTOR = _SECRETNUMBER,
  __module__ = 'secret_number_pb2'
  # @@protoc_insertion_point(class_scope:SecretNumber)
  ))
_sym_db.RegisterMessage(SecretNumber)


# @@protoc_insertion_point(module_scope)
